import "./globals.css";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({ subsets: ["latin"], variable: "--font-jose" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="scroll-smooth" lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={josefin.variable}>
        {children}
      </body>
    </html>
  );
}
